---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chirpstack-rest-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chirpstack-rest-api
  template:
    metadata:
      labels:
        app: chirpstack-rest-api
    spec:
      containers:
        - name: chirpstack-rest-api
          image: chirpstack/chirpstack-rest-api:4
          command: ["chirpstack-rest-api", "--server", "chirpstack:8080", "--bind", "0.0.0.0:8090", "--insecure"]
---
apiVersion: v1
kind: Service
metadata:
  name: chirpstack-rest-api
spec:
  selector:
    app: chirpstack-rest-api
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: chirpstack-rest-api-route
spec:
  parentRefs:
    - name: default-gateway
      namespace: default
  hostnames:
    - "chirpstack-api.your-domain.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: chirpstack-rest-api
          port: 8090
