apiVersion: apps/v1
kind: Deployment
metadata:
  name: chirpstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chirpstack
  template:
    metadata:
      labels:
        app: chirpstack
    spec:
      initContainers:
        - name: init-configuration
          image: busybox
          command: ['sh', '-c', 'cp /config-1/* /config/ && cp /config-2/* /config/']
          volumeMounts:
            - name: chirpstack-config-1
              mountPath: /config-1
            - name: chirpstack-config-2
              mountPath: /config-2
            - name: chirpstack-config
              mountPath: /config
      containers:
        - name: chirpstack
          image: chirpstack/chirpstack:4
          command: ["chirpstack", "-c", "/etc/chirpstack"]
          volumeMounts:
            - name: chirpstack-config
              mountPath: /etc/chirpstack
            - name: lorawan-devices
              mountPath: /opt/lorawan-devices
          env:
            - name: MQTT_BROKER_HOST
              value: "mosquitto"
            - name: REDIS_HOST
              value: "redis"
            - name: POSTGRESQL_HOST
              value: "postgres"
      volumes:
        - name: chirpstack-config-1
          configMap:
            name: chirpstack-config-1
        - name: chirpstack-config-2
          configMap:
            name: chirpstack-config-2
        - name: chirpstack-config
          emptyDir: {}
        - name: lorawan-devices
          persistentVolumeClaim:
            claimName: lorawan-devices-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lorawan-devices-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: chirpstack
spec:
  selector:
    app: chirpstack
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: chirpstack-app-route
spec:
  parentRefs:
    - name: default-gateway
      namespace: default
  hostnames:
    - "chirpstack.your-domain.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: chirpstack
          port: 8080
